# https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml
datadog:
  apiKeyExistingSecret: dd-api-key
  appKeyExistingSecret: dd-app-key
  env:
    - name: DD_LOGS_CONFIG_DOCKER_CONTAINER_USE_FILE
      value: true
    - name: DD_OBSERVABILITY_PIPELINES_WORKER_LOGS_ENABLED
      value: true
    - name: DD_OBSERVABILITY_PIPELINES_WORKER_LOGS_URL
      value: "http://opw-observability-pipelines-worker:8282"
    - name: DD_CONTAINER_EXCLUDE
      value: "name:^datadog-agent* name:^kindnet* name:^kube-proxy* name:^opw* name:^datadog-agent-cluster-agent* name:^kube-api* name:^coredns* name:^kube-controller* name:^kube-scheduler* name:^etcd* image:.*observability-pipelines-worker.* image:.*datadog.* kube_namespace:^kube-system"
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    autoMultiLineDetection: true
  apm:
    portEnabled: true
    socketPath: /var/run/datadog/apm.socket
    hostSocketPath: /var/run/datadog/
  processAgent:
    enabled: true
    processCollection: true
  systemProbe:
    enableTCPQueueLength: false
    enableOOMKill: false
    collectDNSStats: false
  #
  # @ckelner: This doesn't yet exist in the agent helm chart
  #
  # observability_pipelines_worker:
  #   logs:
  #     enabled: true
  #     url: "http://opw-service:8282"
  #

  # if using minikube must be set to false, shouldn't impact other cluster types e.g. EKS, GKE, AKS, etc
  kubelet:
    tlsVerify: false
