sources:
  datadog_agent:
    address: 127.0.0.1:8282
    type: datadog_agent
    multiple_outputs: true

transforms:
  ## The Datadog Agent natively encodes its tags as a comma-separated list
  ## of values that are stored in the string `.ddtags`. To work with
  ## and filter off of these tags, you need to parse that string into
  ## more structured data.
  logs_parse_ddtags:
    type: remap
    inputs:
      - datadog_agent.logs
    source: |
      .ddtags = parse_key_value!(.ddtags, key_value_delimiter: ":", field_delimiter: ",")

  ## The `.status` attribute added by the Datadog Agent needs to be deleted, otherwise
  ## your logs can be miscategorized at intake.
  logs_remove_wrong_level:
    type: remap
    inputs:
      - logs_parse_ddtags
    source: |
      del(.status)

  ## This is a placeholder for your own remap (or other transform)
  ## steps with tags set up. Datadog recommends these tag assignments.
  ## They show which data has been moved over to OP and what still needs
  ## to be moved.
  LOGS_YOUR_STEPS:
    type: remap
    inputs:
      - logs_remove_wrong_level
    source: |
      .ddtags.sender = "observability_pipelines_worker"
      .ddtags.opw_aggregator = get_hostname!()

  ## Before sending data to the logs intake, you must re-encode the
  ## tags into the expected format, so that it appears as if the Agent is
  ## sending it directly.
  logs_finish_ddtags:
    type: remap
    inputs:
      - LOGS_YOUR_STEPS
    source: |
      .ddtags = encode_key_value!(.ddtags, key_value_delimiter: ":", field_delimiter: ",")

sinks:
  datadog_logs:
    type: datadog_logs
    inputs:
      - logs_finish_ddtags
    default_api_key: "${DD_API_KEY}"
    compression: gzip
    buffer:
      type: disk
      max_size: 52589998080
  datadog_archives:
    type: datadog_archives
    inputs:
      - logs_finish_ddtags
    service: gcp_cloud_storage
    bucket: kelnerhax
    gcp_cloud_storage:
      credentials_path: /home/chris_kelner_datadoghq_com/kelnerhax/datadog-sandbox-aed7a56e22d7.json
  datadog_archives_aws:
    type: datadog_archives
    inputs:
      - logs_finish_ddtags
    service: aws_s3
    bucket: kelnerhax-dd
    aws_s3:
      storage_class: "STANDARD"
      region: "us-east-2"
      auth:
        secret_access_key: "${KEL_PERSONAL_AWS_SECRET_KEY}"
        access_key_id: "${KEL_PERSONAL_AWS_ACCESS_KEY}"
