datadog:
  apiKeyExistingSecret:  datadog-secret
  clusterName:  op-k8s-lab
  logs:
    enabled: true
    containerCollectAll: true
    autoMultiLineDetection: true
agents:
  containers:
    agent:
      env: []
