apiVersion: apps/v1
kind: Deployment
metadata:
  name: stderr
spec:
  selector:
    matchLabels:
      app: stderr
  replicas: 1
  template:
    metadata:
      labels:
        app: stderr
    spec:
      containers:
      - name: stderr
        image: kelner/stderr:v5
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              python stderr.py
