apiVersion: apps/v1
kind: Deployment
metadata:
  name: stderr-redirect
spec:
  selector:
    matchLabels:
      app: stderr-redirect
  replicas: 1
  template:
    metadata:
      labels:
        app: stderr-redirect
    spec:
      containers:
      - name: stderr-redirect
        image: kelner/stderr:v5
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              python stderr.py
              2>&1
